---
- src: https://github.com/OULibraries/ansible-role-centos7
  version: v2016-06-29.0
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-mariadb
  version: v2016-04-08.0
  name: OULibraries.mariadb

- src: https://github.com/OULibraries/ansible-role-users
  version: v2016-06-10.0
  name: OULibraries.users

- src: https://github.com/OULibraries/ansible-role-fcrepo3
  name: OULibraries.fcrepo3

- src: https://github.com/OULibraries/ansible-role-drupal
  name: OULibraries.drupal
